name: model-cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python analyse.py
          
          echo "## Total data" > report.md
          echo "<pre>" >> report.md
          cat report/data.txt >> report.md
          echo "</pre>" >> report.md
          
          echo "## Problems per Contest" >> report.md
          cml-publish report/data.png --md >> report.md
          
          cml-send-comment report.md
